In [2]:
#Cau 3

import numpy as np
print(np.__version__)

1.21.5


In [44]:
# Cau 4

arr4 = np.empty(10)

print(arr4)
print("So phan tu:", arr4.size)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306
 1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306
 1.29061142e-306 5.53353523e-322]
So phan tu: 10


In [20]:
# Cau 5

arr5 = np.array([26, 7, 19, 27, 12, 29])

print("So chieu:", arr5.ndim)
print("So phan tu:", arr5.size)

So chieu: 1
So phan tu: 6


In [21]:
# Cau 6

arr6 = np.random.randint(1, 9, size=15)
print(arr6)

print("Phan tu thu 5 trong mang la:", arr6[4])

[7 1 4 8 6 6 7 1 8 2 6 4 6 8 6]
Phan tu thu 5 trong mang la: 6


In [24]:
# Cau 7

arr7 = np.random.random(size=(3, 4))
print(arr7)

print("So chieu:", arr7.ndim)
print("So dong va cot:", arr7.shape)

[[0.45710976 0.47813709 0.12859812 0.15257588]
 [0.09292906 0.205345   0.35171473 0.98308695]
 [0.90341716 0.24066495 0.76311561 0.8743868 ]]
So chieu: 2
So dong va cot: (3, 4)


In [40]:
# Cau 8

arr8 = np.array([[5, 10, 21], [11, 23, 18], [22, 19, 35], [96,22, 26]])
print(arr8)

print("So chieu:", arr8.ndim)
print("So dong va cot:", arr8.shape)

print("Tat ca phan tu dong 2 va 3:\n", arr8[1:3, :])

arr_new = np.array(arr8[:, 2])
print("Vector duoc tao tu gia tri cot 3:\n", arr_new)

arr_new2 = np.array(arr8[1:4, 1:3])
print("Ma tran moi duoc tao tu gia tri sau:\n", arr_new2)

arr8[3, 1] = 30
print("Mang sau khi cap nhat gia tri 22 o dong 4 cot 2 sang 30:\n", arr8)

[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 22 26]]
So chieu: 2
So dong va cot: (4, 3)
Tat ca phan tu dong 2 va 3:
 [[11 23 18]
 [22 19 35]]
Vector duoc tao tu gia tri cot 3:
 [21 18 35 26]
Ma tran moi duoc tao tu gia tri sau:
 [[23 18]
 [19 35]
 [22 26]]
Mang sau khi cap nhat gia tri 22 o dong 4 cot 2 sang 30:
 [[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 30 26]]


In [3]:
# Cau 9

arr9 = np.arange(10, 20)
print(arr9)
print("So luong phan tu:", arr9.size)

arrRe = arr9.reshape(2, 5)
print("Mang ban dau sau khi duoc bien doi:\n", arrRe)
print("So chieu cua mang sau khi duoc bien doi:", arrRe.ndim)

[10 11 12 13 14 15 16 17 18 19]
So luong phan tu: 10
Mang ban dau sau khi duoc bien doi:
 [[10 11 12 13 14]
 [15 16 17 18 19]]
So chieu cua mang sau khi duoc bien doi: 2


In [80]:
# Cau 10

arr10 = np.array([99, 46, 87, 62, 11, 32])
print("Mang ban dau:", arr10)

# Tim phan tu min max
print("Phan tu lon nhat mang:", np.max(arr10))
print("Phan tu nho nhat mang:", np.min(arr10))

# Sap xep mang tang
arr10tang = arr10.copy()
arr10tang.sort()
print("Mang sau khi duoc sap xep tang dan:", arr10tang)

# In cac phan tu o vi tri chan
print("Cac phan tu o vi tri chan la:", end=" ")
## Cach 1
#for i in range(arr10.size):
    #if (i % 2 == 0):
        #print(arr10[i], end=" ")
#print()
## Cach 2
print(arr10[::2])

# Kiem tra phan tu thu 4 la chan hay le
if (arr10[3] % 2 == 0):
    print("Phan tu thu 4 la so chan")
else:
    print("Phan tu thu 4 la so le")
    
# In ra cac phan tu chan trong mang
## Cach 1
#index_chan = np.where(arr10 % 2 == 0)
#print("So phan tu chan trong mang:", arr10[index_chan].size)
## Cach 2
print("So phan tu chan trong mang:", arr10[arr10 % 2 == 0].size)

# Tinh mean, median, sum
print("Gia tri trung binh cua mang:", np.mean(arr10))
print("Gia tri trung vi cua mang:", np.median(arr10))
print("Tong cac gia tri trong mang:", np.sum(arr10))

# Thay gia tri
find = np.where(arr10 == 87)
arr10[find] = np.mean(arr10)
print("Mang sau khi thay gia tri 87 bang trung binh cua mang:", arr10)

# Xoa phan tu
find = np.where(arr10 == 62)
arr10xoa = np.delete(arr10, find)
print("Mang sau khi xoa gia tri 62:", arr10xoa)

Mang ban dau: [99 46 87 62 11 32]
Phan tu lon nhat mang: 99
Phan tu nho nhat mang: 11
Mang sau khi duoc sap xep tang dan: [11 32 46 62 87 99]
Cac phan tu o vi tri chan la: [99 87 11]
Phan tu thu 4 la so chan
So phan tu chan trong mang: 3
Gia tri trung binh cua mang: 56.166666666666664
Gia tri trung vi cua mang: 54.0
Tong cac gia tri trong mang: 337
Mang sau khi thay gia tri 87 bang trung binh cua mang: [99 46 56 62 11 32]
Mang sau khi xoa gia tri 62: [99 46 56 11 32]


In [61]:
# Cau 11

arr11 = np.array([
    [[5, 10, 21], [11, 23, 18], [22, 19, 35]],
    [[50, 10, 41], [61, 23, 28], [42, 11, 25]],
    [[96, 22, 26], [87, 56, 23], [90, 75, 32]]
])
print("Ma tran ban dau:\n", arr11)

# Xuat hai dong cuoi cua ma tran thu nhat
print("Hai dong cuoi cua ma tran thu nhat:\n", arr11[0, 1:3, :])

# Thay cot dau mt2 thanh trung binh cua mt1
arr11_copy = arr11.copy()
arr11_copy[1,:,:1] = np.mean(arr11[0])
print("Ma tran sau khi thay the cot dau cua ma tran thu hai thanh gia tri trung binh cua ma tran thu nhat:\n", arr11_copy)

# Tong cac gia tri o mt3
print("Tong gia tri ma tran thu 3:", np.sum(arr11[2]))

# Thay dong cuoi cua mt3 thanh -1
arr11_copy = arr11.copy()
arr11_copy[2,2:3,:] = -1
print("Ma tran sau khi thay the dong cuoi cua ma tran thu ba thanh -1:\n", arr11_copy)

# Tao ma tran moi tu mt2 va cho biet so chieu cua no
arr_new = np.array(arr11[1])
print("Ma tran moi duoc tao ra tu ma tran thu 2:\n", arr_new)
print("So chieu cua ma tran moi:", arr_new.ndim)

# Chuyen ma tran vua tao thanh vector va them vao cuoi 45
vector = arr_new.ravel()
print("Ma tran vua tao sau khi chuyen thanh vector:", vector)
vector= np.append(vector, 45)
print("Vector sau khi them 45 vao cuoi:", vector)

# Them vao dau 99
vector = np.insert(vector, 0, 99)
print("Vector sau khi them 99 vao dau:", vector)

# Tao list tu ma tran 3 chieu ban dau
list_3d = arr11.tolist()
print("List cac gia tri duoc lay tu mang ba chieu ban dau:\n", list_3d)

Ma tran ban dau:
 [[[ 5 10 21]
  [11 23 18]
  [22 19 35]]

 [[50 10 41]
  [61 23 28]
  [42 11 25]]

 [[96 22 26]
  [87 56 23]
  [90 75 32]]]
Hai dong cuoi cua ma tran thu nhat:
 [[11 23 18]
 [22 19 35]]
Ma tran sau khi thay the cot dau cua ma tran thu hai thanh gia tri trung binh cua ma tran thu nhat:
 [[[ 5 10 21]
  [11 23 18]
  [22 19 35]]

 [[18 10 41]
  [18 23 28]
  [18 11 25]]

 [[96 22 26]
  [87 56 23]
  [90 75 32]]]
Tong gia tri ma tran thu 3: 507
Ma tran sau khi thay the dong cuoi cua ma tran thu ba thanh -1:
 [[[ 5 10 21]
  [11 23 18]
  [22 19 35]]

 [[50 10 41]
  [61 23 28]
  [42 11 25]]

 [[96 22 26]
  [87 56 23]
  [-1 -1 -1]]]
Ma tran moi duoc tao ra tu ma tran thu 2:
 [[50 10 41]
 [61 23 28]
 [42 11 25]]
So chieu cua ma tran moi: 2
Ma tran vua tao sau khi chuyen thanh vector: [50 10 41 61 23 28 42 11 25]
Vector sau khi them 45 vao cuoi: [50 10 41 61 23 28 42 11 25 45]
Vector sau khi them 99 vao dau: [99 50 10 41 61 23 28 42 11 25 45]
List cac gia tri duoc lay tu mang ba ch

In [87]:
# Cau 12

ds = [15, 32, 10, 32, 29, 48, 21]

#Tao vector tu ds
arr12 = np.array(ds)
print("Vector duoc tao tu danh sach tren la:", arr12)

#In ra so phan tu va chieu cua vector
print("So phan tu cua vector:", arr12.size)
print("So chieu cua vector:", arr12.ndim)

# Chuyen vector thanh ma tran 2x4
# arr12.reshape(2, 4)
# Vi co 7 phan tu nen cau lenh nay bi loi

# Them 55 vao vi tri thu 2 va chuyen vector thanh ma tran 4x2
arr12 = np.insert(arr12, 1, 55)
print("Vector sau khi them gia tri 55 vao vi tri thu 2:", arr12)
arr12_new = arr12.reshape(4, 2)
print("Vector sau khi chuyen len thanh ma tran voi kich thuoc 4x2:\n", arr12_new)

# Xuat ra cac phan tu o vi tri le
print("Cac phan tu o vi tri le:", arr12_new.ravel()[1::2])

Vector duoc tao tu danh sach tren la: [15 32 10 32 29 48 21]
So phan tu cua vector: 7
So chieu cua vector: 1
Vector sau khi them gia tri 55 vao vi tri thu 2: [15 55 32 10 32 29 48 21]
Vector sau khi chuyen len thanh ma tran voi kich thuoc 4x2:
 [[15 55]
 [32 10]
 [32 29]
 [48 21]]
Cac phan tu o vi tri le: [55 10 29 21]


In [155]:
#Cau 13

my_dict = {
    "7503": {
        "Họ tên" : "Trần Hải Nam",
        "Năm sinh" : "2000",
        "Giới tính" : "Nam"
    },
    "3010": {
        "Họ tên" : "Đỗ Minh Hạnh",
        "Năm sinh" : "2002",
        "Giới tính" : "Nữ"
    },
    "6198": {
        "Họ tên" : "Trần Anh Tài",
        "Năm sinh" : "2001",
        "Giới tính" : "Nam"
    }
}

# Chuyen dictionary thanh array
arr13 = np.array([(key, value['Họ tên'], value['Năm sinh'], value['Giới tính']) for key, value in my_dict.items()])
print("Mang ban dau:\n", arr13)

# Them mot nguoi vao
arr13 = np.concatenate((arr13, [['2876', 'Lê Trung Tín', '2002', 'Nam']]), axis=0)
print("Mang sau khi them:\n", arr13)

# Dem nguoi sinh nam 2002
find2002 = np.where(arr13[:,2:3] == "2002")
print("So nguoi sinh nam 2002:", len(find2002)) #arr13[find].size dung cung duoc

#Dem nam nu
findNam = np.where(arr13[:,3:4] == "Nam")
print("So nam:", len(findNam))
findNu = np.where(arr13[:,3:4] == "Nữ")
print("So nu:", len(findNu))

Mang ban dau:
 [['7503' 'Trần Hải Nam' '2000' 'Nam']
 ['3010' 'Đỗ Minh Hạnh' '2002' 'Nữ']
 ['6198' 'Trần Anh Tài' '2001' 'Nam']]
Mang sau khi them:
 [['7503' 'Trần Hải Nam' '2000' 'Nam']
 ['3010' 'Đỗ Minh Hạnh' '2002' 'Nữ']
 ['6198' 'Trần Anh Tài' '2001' 'Nam']
 ['2876' 'Lê Trung Tín' '2002' 'Nam']]
So nguoi sinh nam 2002: 2
So nam: 2
So nu: 2


In [139]:
count = 0

for i in arr13[:,2:3]:
    if (i == "2002"):
        count += 1
        
print(count)

2


In [150]:
a = np.where(arr13[:,2:3] == "2002")
print(a)
print(len(a))

(array([1, 3], dtype=int64), array([0, 0], dtype=int64))
2


In [153]:
arr13[:,3:4]

array([['Nam'],
       ['Nữ'],
       ['Nam'],
       ['Nam']], dtype='<U12')